apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      labels: 
        app: nginx
    spec:    
  #  hostNetwork: true
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: ip-nginx
spec:
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: pod5
spec:
  hostNetwork: true
  containers:
  - name: curl
    image: curlimages/curl
    command: ["curl", "-s", "http://10.244.0.141"]
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 5; curl -s localhost; done"]
  
  #  command: ["kubectl exec pod5 -- curl -s http://10.244.0.141"]

  